server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: 86400000
    refresh-expiration-in-ms: 604800000